playground/djangotest/src/djangotest/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth import views as auth_views
from djangotest.views import hello,hours_ahead,current_datetime
from django.contrib.auth.views import login, logout
from djangotest.todo.views import *
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
                       

                        url('^hello/$', hello),
                        url('^current/$', current_datetime),
                        
                        url('^hour/(\d{1,2})/$', hours_ahead),
                                
                        url (r'^accounts/login/$', login),
                        url (r'^accounts/logout/$', logout),

                           url(r'^mine/$', view_list,{'list_slug':'mine'},name="todo-mine"),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/delete$', del_list,name="todo-del_list"),
    url(r'^task/(?P<task_id>\d{1,6})$', view_task, name='todo-task_detail'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)$', view_list, name='todo-incomplete_tasks'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/completed$', view_list, {'view_completed':1},name='todo-completed_tasks'),    
    url(r'^add_list/$', add_list,name="todo-add_list"),
    url(r'^search/$', search,name="todo-search"),    
    url(r'^$', list_lists,name="todo-lists"),
    
    # View reorder_tasks is only called by JQuery for drag/drop task ordering
    url(r'^reorder_tasks/$', reorder_tasks,name="todo-reorder_tasks"),
    
    url(r'^ticket/add/$', external_add,name="todo-external-add"),    
    url(r'^recent/added/$', view_list,{'list_slug':'recent-add'},name="todo-recently_added"),
    url(r'^recent/completed/$', view_list,{'list_slug':'recent-complete'},name="todo-recently_completed"),
    
    
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),    
                       
    
    # Examples:
    # url(r'^$', 'djangotest.views.home', name='home'),
    # url(r'^djangotest/', include('djangotest.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

playground/djangotest/src/djangotest/todo/models.py
from django.db import models
from django.forms.models import ModelForm
from django import forms
from django.contrib import admin
from django.contrib.auth.models import User,Group
import string, datetime
from django.template.defaultfilters import slugify


class List(models.Model):
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60,editable=False)
    # slug = models.SlugField(max_length=60)    
    group = models.ForeignKey(Group)
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)

        super(List, self).save(*args, **kwargs)

    

    def __unicode__(self):
        return self.name
        
    # Custom manager lets us do things like Item.completed_tasks.all()
    objects = models.Manager()
    
    def incomplete_tasks(self):
        # Count all incomplete tasks on the current list instance
        return Item.objects.filter(list=self,completed=0)
        
    class Meta:
        ordering = ["name"]        
        verbose_name_plural = "Lists"
        
        # Prevents (at the database level) creation of two lists with the same name in the same group
        unique_together = ("group", "slug")
        
        


        
class Item(models.Model):
    title = models.CharField(max_length=140)
    list = models.ForeignKey(List)
    created_date = models.DateField(auto_now=True, auto_now_add=True)
    due_date = models.DateField(blank=True,null=True,)
    completed = models.BooleanField()
    completed_date = models.DateField(blank=True,null=True)
    created_by = models.ForeignKey(User, related_name='created_by')
    assigned_to = models.ForeignKey(User, related_name='todo_assigned_to')
    note = models.TextField(blank=True,null=True)
    priority = models.PositiveIntegerField(max_length=3)
    
    # Model method: Has due date for an instance of this object passed?
    def overdue_status(self):
        "Returns whether the item's due date has passed or not."
        if datetime.date.today() > self.due_date :
            return 1

    def __unicode__(self):
        return self.title
        
    # Auto-set the item creation / completed date
    def save(self):
        # If Item is being marked complete, set the completed_date
        if self.completed :
            self.completed_date = datetime.datetime.now()
        super(Item, self).save()


    class Meta:
        ordering = ["priority"]        
        

class Comment(models.Model):    
    """
    Not using Django's built-in comments becase we want to be able to save 
    a comment and change task details at the same time. Rolling our own since it's easy.
    """
    author = models.ForeignKey(User)
    task = models.ForeignKey(Item)
    date = models.DateTimeField(default=datetime.datetime.now)
    body = models.TextField(blank=True)
    
    def __unicode__(self):        
        return '%s - %s' % (
                self.author, 
                self.date, 
                )        

playground/djangotest/src/djangotest/todo/views.py
from django import forms 
from django.shortcuts import render_to_response
from djangotest.todo.models import Item, List, Comment
from djangotest.todo.forms import AddListForm, AddItemForm, EditItemForm, AddExternalItemForm, SearchForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.contrib import auth
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.sites.models import Site
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import Q
from django.contrib import messages

import datetime

# Need for links in email templates
current_site = Site.objects.get_current() 


@login_required
def list_lists(request):
    
    """
    Homepage view - list of lists a user can view, and ability to add a list.
    """
    
    # Make sure user belongs to at least one group.
    group_count = request.user.groups.all().count()
    if group_count == 0:
        messages.error(request, "You do not yet belong to any groups. Ask your administrator to add you to one.")                        
        

    # Only show lists to the user that belong to groups they are members of.
    # Superusers see all lists
    if request.user.is_superuser:
        list_list = List.objects.all().order_by('group','name')
    else:
        list_list = List.objects.filter(group__in=request.user.groups.all).order_by('group','name')
    
    # Count everything
    list_count = list_list.count()
    
    # Note admin users see all lists, so count shouldn't filter by just lists the admin belongs to
    if request.user.is_superuser :
        item_count = Item.objects.filter(completed=0).count()        
    else:
        item_count = Item.objects.filter(completed=0).filter(list__group__in=request.user.groups.all()).count()

    return render_to_response('todo/list_lists.html', locals(), context_instance=RequestContext(request))  
    

@login_required
def del_list(request,list_id,list_slug):

    """
    Delete an entire list. Danger Will Robinson! Only staff members should be allowed to access this view.
    """
    
    if request.user.is_staff:
        can_del = 1

    # Get this list's object (to derive list.name, list.id, etc.)
    list = get_object_or_404(List, slug=list_slug)

    # If delete confirmation is in the POST, delete all items in the list, then kill the list itself
    if request.method == 'POST':
        # Can the items
        del_items = Item.objects.filter(list=list.id)
        for del_item in del_items:
            del_item.delete()
        
        # Kill the list
        del_list = List.objects.get(id=list.id)
        del_list.delete()
        
        # A var to send to the template so we can show the right thing
        list_killed = 1

    else:
        item_count_done = Item.objects.filter(list=list.id,completed=1).count()
        item_count_undone = Item.objects.filter(list=list.id,completed=0).count()
        item_count_total = Item.objects.filter(list=list.id).count()    
    
    return render_to_response('todo/del_list.html', locals(), context_instance=RequestContext(request))


@login_required
def view_list(request,list_id=0,list_slug=None,view_completed=0):
    
    """
    Display and manage items in a task list
    """
    
    # Make sure the accessing user has permission to view this list.
    # Always authorize the "mine" view. Admins can view/edit all lists.

    if list_slug == "mine"  or list_slug == "recent-add" or list_slug == "recent-complete" :
        auth_ok =1
    else: 
        list = get_object_or_404(List, slug=list_slug)
        listid = list.id    
        
        # Check whether current user is a member of the group this list belongs to.
        if list.group in request.user.groups.all() or request.user.is_staff or list_slug == "mine" :
            auth_ok = 1   # User is authorized for this view
        else: # User does not belong to the group this list is attached to
            messages.error(request, "You do not have permission to view/edit this list.")                                    

        
    # First check for items in the mark_done POST array. If present, change
    # their status to complete.
    if request.POST.getlist('mark_done'):
        done_items = request.POST.getlist('mark_done')
        # Iterate through array of done items and update its representation in the model
        for thisitem in done_items:
            p = Item.objects.get(id=thisitem)
            p.completed = 1
            p.completed_date = datetime.datetime.now()
            p.save()
            messages.success(request, "Item \"%s\" marked complete." % p.title)                                             


    # Undo: Set completed items back to incomplete
    if request.POST.getlist('undo_completed_task'):
        undone_items = request.POST.getlist('undo_completed_task')
        for thisitem in undone_items:
            p = Item.objects.get(id=thisitem)
            p.completed = 0
            p.save()
            messages.success(request, "Previously completed task \"%s\" marked incomplete." % p.title)


    # And delete any requested items
    if request.POST.getlist('del_task'):
        deleted_items = request.POST.getlist('del_task')
        for thisitem in deleted_items:
            p = Item.objects.get(id=thisitem)
            p.delete()
            messages.success(request, "Item \"%s\" deleted." % p.title)         

    # And delete any *already completed* items
    if request.POST.getlist('del_completed_task'):
        deleted_items = request.POST.getlist('del_completed_task')
        for thisitem in deleted_items:
            p = Item.objects.get(id=thisitem)
            p.delete()
            messages.success(request, "Deleted previously completed item \"%s\"."  % p.title)                       


    thedate = datetime.datetime.now()
    created_date = "%s-%s-%s" % (thedate.year, thedate.month, thedate.day)


    # Get list of items with this list ID, or filter on items assigned to me, or recently added/completed
    if list_slug == "mine":
        task_list = Item.objects.filter(assigned_to=request.user, completed=0)
        completed_list = Item.objects.filter(assigned_to=request.user, completed=1)
        
    elif list_slug == "recent-add":
        # We'll assume this only includes uncompleted items to avoid confusion.
        # Only show items in lists that are in groups that the current user is also in.
        task_list = Item.objects.filter(list__group__in=(request.user.groups.all()),completed=0).order_by('-created_date')[:50]
        # completed_list = Item.objects.filter(assigned_to=request.user, completed=1)   
        
    elif list_slug == "recent-complete":
        # Only show items in lists that are in groups that the current user is also in.
        task_list = Item.objects.filter(list__group__in=request.user.groups.all(),completed=1).order_by('-completed_date')[:50]
        # completed_list = Item.objects.filter(assigned_to=request.user, completed=1)             


    else:
        task_list = Item.objects.filter(list=list.id, completed=0)
        completed_list = Item.objects.filter(list=list.id, completed=1)


    if request.POST.getlist('add_task') :
        form = AddItemForm(list, request.POST,initial={
        'assigned_to':request.user.id,
        'priority':999,
        })
        
        if form.is_valid():
            # Save task first so we have a db object to play with
            new_task = form.save()

            # Send email alert only if the Notify checkbox is checked AND the assignee is not the same as the submittor
            # Email subect and body format are handled by templates
            if "notify" in request.POST :
                if new_task.assigned_to != request.user :
                                        
                    # Send email
                    email_subject = render_to_string("todo/email/assigned_subject.txt", { 'task': new_task })                    
                    email_body = render_to_string("todo/email/assigned_body.txt", { 'task': new_task, 'site': current_site, })
                    try:
                        send_mail(email_subject, email_body, new_task.created_by.email, [new_task.assigned_to.email], fail_silently=False)
                    except:
                        messages.error(request, "Task saved but mail not sent. Contact your administrator.")
                        

            messages.success(request, "New task \"%s\" has been added." % new_task.title)                       
            
            return HttpResponseRedirect(request.path)

    else:
        if list_slug != "mine" and list_slug != "recent-add" and list_slug != "recent-complete" : # We don't allow adding a task on the "mine" view
            form = AddItemForm(list, initial={
                'assigned_to':request.user.id,
                'priority':999,
                } )

    if request.user.is_staff:
        can_del = 1

    return render_to_response('todo/view_list.html', locals(), context_instance=RequestContext(request))


@login_required
def view_task(request,task_id):

    """
    View task details. Allow task details to be edited.
    """

    task = get_object_or_404(Item, pk=task_id)
    comment_list = Comment.objects.filter(task=task_id)
        
    # Before doing anything, make sure the accessing user has permission to view this item.
    # Determine the group this task belongs to, and check whether current user is a member of that group.
    # Admins can edit all tasks.

    if task.list.group in request.user.groups.all() or request.user.is_staff:
        
        auth_ok = 1
        if request.POST:
             form = EditItemForm(request.POST,instance=task)

playground/djangotest/src/djangotest/templates/todo/add_external_task.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}File Ticket{% endblock %}

{% block content %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}



<h2>{{ task }}</h2>

<form action="" method="POST">
{% csrf_token %}	


{% if task.note %}
<div class="task_note"><strong>Note:</strong> {{ task.note|safe|urlize|linebreaks }}</div>    
{% endif %}

<div id="TaskEdit">
<h3>File Trouble Ticket</h3>
<p>Trouble with a computer or other technical system at the J-School? <br />
Use this form to report the difficulty - we'll get right back to you. </p>

{% if form.errors %}

    {% for error in form.errors %}        
    <ul class="errorlist">
        <li><strong>The {{ error|escape }} field is required.</strong></li>
    </ul>
    {% endfor %}
<br />

{% endif %}


<table>
    {{ form.management_form }}
    {{ form.id }}

<tr>    
    <td>Summary:</td>

    <td>{{ form.title }} <br />
    Include the workstation number in your summary, e.g. <br />
    "Radio Lab # 4: Purple smoke pouring out the back."
     </td>
</tr>


<tr>    
    <td valign="top">Note:</td>

    <td valign="top">{{ form.note }}<br />
    Please describe the problem.   </td>
</tr>

<tr>    
    <td>Priority:</td>
    
    <td>{{ form.priority }} <br />
    Enter a number between 1 and 5, <br />
    where 5 is highest ("Computer is on fire = True").
     </td>
</tr>
    
</table>   
<p><input type="submit" class="todo-button" name="add_task" value="Submit"></p>
</div>


</form>

 
{% endblock %}

playground/djangotest/src/djangotest/templates/todo/add_list.html
{% extends "todo/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Add Todo List{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


<h2>Add a list:</h2>

<form action="" method="post">
	{% csrf_token %}	
<table>{{ form }}</table>
<p><input type="submit" value="Submit" class="todo-button"></p>
</form>
 
{% endblock %}

playground/djangotest/src/djangotest/templates/todo/base.html
{% extends "base.html" %}
{% block page_heading %}GTD (Getting Things Done){% endblock %}
{% block extrahead %}
<!-- CSS and JavaScript for django-todo -->
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}todo/css/styles.css" />

<script src="{{STATIC_URL}}todo/js/ui.datepicker.js" type="text/javascript"></script>
<script src="{{STATIC_URL}}todo/js/jquery.tablednd_0_5.js" type="text/javascript"></script> 
<link type="text/css" href="{{STATIC_URL}}todo/js/jquery-ui-1.7.1.custom.css" rel="Stylesheet" />

<script type="text/javascript" charset="utf-8">
    // thedate.x comes from the edit_task view. If this is a new entry, 
    // thedate won't be present and datepicker will fall back on the default (today).
    $(document).ready(function(){
        $('#id_due_date').datepicker({defaultDate: new Date({{thedate.year}}, {{thedate.month}} - 1, {{thedate.day}}),});
     });

</script>

{% endblock extrahead %}

playground/djangotest/src/djangotest/templates/todo/del_list.html
{% extends "base.html" %}

{% block title %}{{ list_title }} to-do items{% endblock %}

{% block content %}

{# Only admins can delete lists. #}
{% ifequal can_del 1 %}


    {% if list_killed %}

       <p> {{ list.name }} is gone.</p>
   
        <a href="{% url todo-lists %}">Return to lists</a>   

    {% else %}

        <h1>Delete entire list: {{ list.name }} ?</h1>

        <p>Category tally:</p>

         <ul>   
            <li>Incomplete: {{ item_count_undone }} </li>
            <li>Complete: {{ item_count_done }} </li>
            <li><strong>Total: {{ item_count_total }}</strong> </li>
         </ul>   
 
        <p> ... all of which will be irretrievably <strong>blown away</strong>. Are you sure you want to do that?</p>

        <form action="" method="post" accept-charset="utf-8">
		{% csrf_token %}
 
            <input type="hidden" name="list" value="{{ list.id }}" id="some_name">
         <p><input type="submit" name="delete-confirm" value="Do it! &rarr;" class="todo-button"> </p>
        </form>


        <a href="{% url todo-incomplete_tasks list.id list_slug %}">Return to list: {{ list.name }}</a>

    {% endif %}


{% else %}

    <p>Sorry, you don't have permission to delete lists. Please contact your group administrator.</p>

{% endifequal %}




   
   
	
{% endblock %}

playground/djangotest/src/djangotest/templates/todo/list_lists.html
{% extends "todo/base.html" %}

{% block title %}{{ list_title }} Todo Lists{% endblock %}

{% block content %}


    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

   <h1>To-do Lists</h1>
   
   <p>{{ item_count }} items in {{ list_count }} lists</p>

   	{% regroup list_list by group as section_list %}

    {% for group in section_list %}
        <h3>{{ group.grouper }}</h3>
        <ul>
            {% for item in group.list %}
   	            <li><a class="todo" href="{% url todo-incomplete_tasks item.id item.slug %}">{{ item.name }} </a> ({{ item.incomplete_tasks.count }}/{{ item.item_set.count }})</li>
            {% endfor %}
        </ul>

    {% endfor %}

    

    <div class="todo-break">
    &nbsp;
    </div>

    <p><a href="{% url todo-add_list %}">Create new todo list</a></p>
	
{% endblock %}

playground/djangotest/src/djangotest/templates/todo/search_results.html
{% extends "todo/base.html" %}

{% block title %}Search results{% endblock %}
{% block body_id %}post_search{% endblock %}


{% block content_title %}
  <h2 class="page_title">Search</h2>
{% endblock %}


{% block content %}

  {% if message %}
  <p class="message">{{ message }}</p>
  {% endif %}
  
  {% if found_items %}
  <h2>{{found_items.count}} search results for term: "{{ query_string }}"</h2>
  <div class="post_list">

    {% for f in found_items %}
    <p><strong><a href="{% url todo-task_detail f.id %}">{{ f.title }}</a></strong><br />
        
        <span class="minor">
        On list: <a href="{% url todo-incomplete_tasks f.list.id f.list.slug %}">{{ f.list }}</a><br />
        Assigned to: {{ f.assigned_to }} (created by: {{ f.created_by }})<br />
        Complete: {{ f.completed|yesno:"Yes,No" }}
        </span>        
    </p>
    {% endfor %}
  </div>
  {% else %}
 <h2> No results to show, sorry.</h2>
  
  {% endif %}
{% endblock %}

playground/djangotest/src/djangotest/templates/todo/view_list.html
{% extends "todo/base.html" %}

{% block title %}Todo List: {{ list.name }}{% endblock %}

{% block content %}

<script type="text/javascript">

function order_tasks(data) {
    // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered 
    // data in a list. We pass that list as an object called "data" to a Django view 
    // to save the re-ordered data into the database.

    $.post("{% url todo-reorder_tasks %}", data, "json");
    return false;
};

$(document).ready(function() {
    // Initialise the task table for drag/drop re-ordering
    $("#tasktable").tableDnD();
    
    $('#tasktable').tableDnD({
        onDrop: function(table, row) {
            order_tasks($.tableDnD.serialize());
        }
    });
    
    // Initially hide the Add Task form
    $('#AddTask').hide();
    
    // toggle slide to show the Add Task form when link clicked
    $('#slideToggle').click(function(){
        $(this).siblings('#AddTask').slideToggle();
    });
});

</script>


    {% ifequal list_slug "mine" %}
        <h1>Tasks assigned to {{ request.user }}</h1>    
    {% else %}
    {% ifequal auth_ok 1 %}
       <h1>Tasks filed under "{{ list.name }}"</h1>
       <p>This list belongs to group {{ list.group }}</p>
    {% endifequal %}
    {% endifequal %}

 
   {% if messages %}
   <ul class="messages">
       {% for message in messages %}
       <li>{{ message }}</li>
       {% endfor %}
   </ul>
   {% endif %}   


   {% ifequal auth_ok 1 %}
   <form action="" method="POST">
	{% csrf_token %}	
   
   {# Only show task adder if viewing a proper list #}
   {% ifnotequal list_slug "mine" %}
   <h2 style="margin-bottom:0px;" id="slideToggle" >&rarr; Click to add task &larr;</h2>
   
   <div id="AddTask">	    
	    <table class="nocolor" border="0" cellspacing="5" cellpadding="5">
	       <tr>
	           <td>{{ form.title.errors }}</td>
	           <td>{{ form.due_date.errors }}</td>
	       </tr>
	       <tr>
	           <td><label for="id_title">Task:</label> {{ form.title }}</td>
	           <td><label for="id_due_date">Due date:</label> {{ form.due_date }}</td>
	           <td><label for="id_assigned">Assign to:</label> {{ form.assigned_to }}</td>
	           <td><label for="id_notify">Notify*:</label> <input type="checkbox" checked="checked" name="notify" value="1" id="notify"></td>
 	       </tr>
	       <tr>
	           <td colspan="5"><label for="id_note">Note:</label> {{ form.note }}
	               <p class="minor">*Email notifications will only be sent if task is assigned to someone besides yourself.</p>
	           </td>
 	       </tr> 	       
	    </table>
	
        <input type="hidden" name="priority" value="999" id="id_priority">
        <input type="hidden" name="created_by" value="{{ request.user.id }}" id="id_created_by">
        <input type="hidden" name="list" value="{{ listid }}" id="id_list">
        <input type="hidden" name="created_date" value="{{ created_date }}" id="id_created_date">	        
	    
	    <p><input type="submit" name="add_task" value="Add task" class="todo-button"></p>
    </div>	    
	    
        {% endifnotequal %}
        
        
    {% ifequal view_completed 0  %}

	<h3>Incomplete tasks :: Drag rows to set priorities</h3>
	   
	<table border="0" id="tasktable">	
        <tr>
            <th>Done</th>             
            <th>Task</th> 
            <th>Created</th> 
            <th>Due on</th>                         
            <th>Owner</th> 
            <th>Assigned</th>   
            <th>Note</th>   
            <th>Comm</th>                            
 
            {% ifequal list_slug "mine" %}
            <th>List</th>   
             {% endifequal %}            
                                 
            <th>Del</th>             
        </tr>
		{% for task in task_list %}
	        <tr class="{% cycle 'row1' 'row2' %}" id="{{ task.id }}">
	            <td><input type="checkbox" name="mark_done" value="{{ task.id }}" id="mark_done_{{ task.id }}">   </td> 
	            <td><a href="{% url todo-task_detail task.id %}">{{ task.title|truncatewords:20 }}</a></td> 
	            <td>{{ task.created_date|date:"m/d/Y" }}</td> 
	            <td>
	            {% if task.overdue_status %}<span class="overdue">{% endif %}
	                {{ task.due_date|date:"m/d/Y" }}  
	            {% if task.overdue_status %}</span>{% endif %}	                
	            </td>
	            <td>{{ task.created_by }}</td> 
	            <td>{{ task.assigned_to }}</td>
	            <td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
	            <td style="text-align:center;">{% ifnotequal task.comment_set.all.count 0  %}{{ task.comment_set.all.count }}{% endifnotequal %}
                   
	            </td>	            
	            {% ifequal list_slug "mine" %}
                <td><a href="{% url todo-incomplete_tasks task.list.id task.list.slug %}">{{ task.list }}</a></td>   
                {% endifequal %}
                       
	            <td><input type="checkbox" name="del_task" value="{{ task.id }}" id="del_task_{{ task.id }}">   </td> 	            
            </tr>
	    {% endfor %}
	</table>   
    <p><input type="submit" name="mark_tasks_done" value="Continue..."  class="todo-button"></p>
    
    <p><a  class="todo" href="{% url todo-completed_tasks list_id list_slug %}">View completed tasks</a></p>
    {% endifequal %}    

    {% ifequal view_completed 1 %}
	<h3>Completed tasks</h3> 

	<table border="0"  id="tasktable">	
        <tr>
            <th>Undo</th> 
            <th>Task</th> 
            <th>Created</th> 
            <th>Completed on</th>   
            <th>Note</th>   
            <th>Comm</th>            
            {% ifequal list_slug "mine" %}
            <th>List</th>   
             {% endifequal %}                       
            <th>Del</th>                
        </tr>

        
		{% for task in completed_list %}
	        <tr class="{% cycle 'row1' 'row2' %}">     
	            <td><input type="checkbox" name="undo_completed_task" value="{{ task.id }}" id="id_undo_completed_task{{ task.id }}">   </td> 	            	            	            
	            <td><a href="{% url todo-task_detail task.id %}">{{ task.title|truncatewords:20 }}</a></td> 
	            <td>{{ task.created_date|date:"m/d/Y" }}</td> 
	            <td>{{ task.completed_date|date:"m/d/Y" }}</td>	     
	            <td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
	            <td style="text-align:center;">{% ifnotequal task.comment_set.all.count 0  %}{{ task.comment_set.all.count }}{% endifnotequal %}
	               
	            <td><input type="checkbox" name="del_completed_task" value="{{ task.id }}" id="del_completed_task_{{ task.id }}">   </td> 	            	            
            </tr>
	    {% endfor %}

	</table>
	<p><input type="submit" name="deldonetasks" value="Continue..."  class="todo-button"></p>
	</form> 
    <p><a  class="todo" href="{% url todo-incomplete_tasks list_id list_slug %}">View incomplete tasks</a></p>
    {% endifequal %}    
	
	{% ifequal can_del 1 %}
	{% ifnotequal list_slug "mine" %}    
	   <p><a class="todo" href="{% url todo-del_list list_id list_slug %}">Delete this list</a></p>
	{% endifnotequal %}
	{% endifequal %}
	
    {% endifequal %}
{% endblock %}